### ISSUE TITLE
Modal Issue

### ISSUE THREAD

**Issue by rofickachmad** [rofickachmad/dewa-project#82]
Modal-form pada tarif tidak bisa di reset, permasalahan muncul ketika setelah selesai membuka modal dari edit kemudian membuka modal pada tarif baru, isi dari form tidak tereset alias masih ada data dari modal edit.

**Comment by roniwahyu** [comment]
ngelu iki aqku

**Comment by rofickachmad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 82](https://trello.com/c/atFS2jNM/2-issue-82)

**Comment by rofickachmad** [comment]
yang sudah saya coba untuk fix modal, di module prodi dan kelompokmhs, yang tarif masih belum fix :'(
