### ISSUE TITLE
Report Penagihan Issue

### ISSUE THREAD

**Issue by rofickachmad** [rofickachmad/dewa-project#94]
- Report (belum tertagih, dan sudah tertagih, belumvalidas dan sudah validasi)
report:

**Comment by rofickachmad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 94](https://trello.com/c/kwL9Y4cJ/14-issue-94)

**Comment by roniwahyu** [comment]
sampun mantun pakdhe
