### ISSUE TITLE
Tabel Tagihan

### ISSUE THREAD

**Issue by roniwahyu** [rofickachmad/dewa-project#98]
Pada saat buka Tabel tagihan,kode item yang telah ditagihkan masih muncul,mestinya setelah ditagihkan dan divalidasi,maka kode item tidak muncul kembali, atau pada saat ditagihkan ada status tagihan

**Comment by rofickachmad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 98](https://trello.com/c/0NspBz09/18-issue-98)
